"use client";
import {useEffect,useRef,useState} from "react";
type Team="RED"|"BLUE"|"GREEN"|"YELLOW"; type Ch=1|2|3|4;
type P={team:Team;solved:Ch[];attempts:Partial<Record<Ch,number>>;cooldowns:Partial<Record<Ch,number>>};
type View="login"|"resume"|"brief"|"case"|"fail"|"reward"|"status"|"final"|"pin"|"host";
const G={
RED:{key:"LOTUS47",route:[["8317",1],["4128",2],["7619",3],["2527",4]] as [string,Ch][],time:"11:48 PM",courier:["LEELA VARMA","T27"],trip:["DELHI","BOMBAY","COLOMBO","LONDON","VANCOUVER","SAN FRANCISCO"]},
BLUE:{key:"MONSOON47",route:[["4137",2],["2536",4],["8326",1],["7628",3]] as [string,Ch][],time:"11:51 PM",courier:["LAKSHMAN VOHRA","S14"],trip:["DELHI","KARACHI","ALEXANDRIA","LONDON","BOSTON","SAN FRANCISCO"]},
GREEN:{key:"CEDAR47",route:[["7646",3],["8344",1],["2554",4],["4155",2]] as [string,Ch][],time:"11:54 PM",courier:["LALITA VAIDYA","R32"],trip:["DELHI","CALCUTTA","SINGAPORE","LONDON","HONOLULU","SAN FRANCISCO"]},
YELLOW:{key:"SAFFRON47",route:[["2563",4],["7655",3],["4164",2],["8353",1]] as [string,Ch][],time:"11:57 PM",courier:["LOKESH VERMA","G18"],trip:["DELHI","MADRAS","CAIRO","LONDON","NEW YORK","SAN FRANCISCO"]}} as const;
const C:Record<Ch,{r:string;t:string;q:string;d:string}>={1:{r:"I",t:"THE MISSING HOUR",q:"AT WHAT EXACT TIME WAS THE INDRA DIAMOND REMOVED FROM SECURED TREASURY CUSTODY?",d:"8"},2:{r:"II",t:"THE COURIER",q:"IDENTIFY THE INDIVIDUAL WHO CARRIED THE BLACK DIPLOMATIC CASE FROM THE SECURED VAULT.",d:"4"},3:{r:"III",t:"THE JOURNEY",q:"RECONSTRUCT THE SIX LOCATIONS THROUGH WHICH THE SECURED DIPLOMATIC CONSIGNMENT PASSED, IN CHRONOLOGICAL ORDER.",d:"7"},4:{r:"IV",t:"THE CUSTODIAN",q:"WHAT ONE-WORD CODENAME WAS ASSIGNED TO THE CLASSIFIED OPERATION?",d:"2"}};
const KEY="indra-47-state",clean=(s:string)=>s.toUpperCase().trim().replace(/[^A-Z0-9]/g,"");
const city=(s:string)=>({MUMBAI:"BOMBAY",KOLKATA:"CALCUTTA",CHENNAI:"MADRAS"}[clean(s)]||clean(s));
function Frag({ch,all=false}:{ch?:Ch;all?:boolean}){return <div className={`fragment q${ch||0} ${all?"all":""}`}><div className="quarters"><i/><i/><i/><i/></div><b>{all?"FINAL LOCATION RECORD":`FRAGMENT ${ch&&C[ch].r}`}</b></div>}
function Header(){const [muted,setMuted]=useState(true),hold=useRef<ReturnType<typeof setTimeout>|null>(null);const cancel=()=>{if(hold.current)clearTimeout(hold.current)};return <header><span>TREASURY SECURITY DIVISION · ARCHIVE 47</span><button onPointerDown={()=>hold.current=setTimeout(()=>window.dispatchEvent(new Event("indra-host")),5000)} onPointerUp={cancel} onPointerLeave={cancel}>CASE 47-ID</button><button className="sound" onClick={()=>setMuted(!muted)}>SOUND {muted?"OFF":"ON"}</button></header>}
function Shell({children,stamp}:{children:React.ReactNode;stamp?:string}){return <main><Header/><section className="paper">{stamp&&<div className="stamp">{stamp}</div>}{children}</section><footer>FICTIONAL ARCHIVAL SYSTEM · AUTHORIZED PERSONNEL ONLY</footer></main>}
function Primary({children,onClick,disabled=false}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button disabled={disabled} className="primary" onClick={onClick}>{children}<span>→</span></button>}
const countdown=(ms:number)=>`${String(Math.floor(Math.ceil(ms/1000)/60)).padStart(2,"0")}:${String(Math.ceil(ms/1000)%60).padStart(2,"0")}`;
export default function App(){
 const [view,setView]=useState<View>("login"),[p,setP]=useState<P|null>(null),[ready,setReady]=useState(false),[input,setInput]=useState(""),[override,setOverride]=useState(""),[trip,setTrip]=useState(["","","","","",""]),[timeDigits,setTimeDigits]=useState(["","","",""]),[meridiem,setMeridiem]=useState<"AM"|"PM">("PM"),[msg,setMsg]=useState(""),[now,setNow]=useState(Date.now()),[pin,setPin]=useState(""),[hostTeam,setHostTeam]=useState<Team>("RED"),[confirm,setConfirm]=useState(false);
 useEffect(()=>{try{const s=localStorage.getItem(KEY);if(s){setP(JSON.parse(s));setView("resume")}}catch{}setReady(true)},[]);useEffect(()=>{const x=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(x)},[]);useEffect(()=>{const open=()=>setView("pin");window.addEventListener("indra-host",open);return()=>window.removeEventListener("indra-host",open)},[]);
 const save=(x:P)=>{setP(x);localStorage.setItem(KEY,JSON.stringify(x))},route=p?G[p.team].route:null,current=route?.find(x=>!p?.solved.includes(x[1])),dossier=current?.[0],ch=current?.[1],cool=ch&&p?.cooldowns[ch]?Math.max(0,p.cooldowns[ch]!-now):0;
 const auth=()=>{const t=(Object.keys(G) as Team[]).find(x=>G[x].key===clean(input));if(!t){setMsg("ACCESS CREDENTIAL NOT RECOGNIZED");return}save({team:t,solved:[],attempts:{},cooldowns:{}});setMsg("");setView("brief")};
 const check=()=>{if(!p||!ch||cool)return;const g=G[p.team];let ok=false;if(ch===1)ok=clean(`${timeDigits.join("")} ${meridiem}`)===clean(g.time);if(ch===2)ok=(g.courier as readonly string[]).some(x=>clean(x)===clean(input));if(ch===3)ok=g.trip.every((x,i)=>city(trip[i])===x);if(ch===4)ok=["ASHIRWAD","AASHIRWAD","ASHIRVAD","ASHIRVAAD"].includes(clean(input));if(ok){save({...p,solved:[...p.solved,ch],attempts:{...p.attempts,[ch]:0}});setInput("");setTrip(["","","","",""]);setTimeDigits(["","","",""]);setMeridiem("PM");setView("reward")}else{const n=(p.attempts[ch]||0)+1;save({...p,attempts:{...p.attempts,[ch]:n},cooldowns:n>=3?{...p.cooldowns,[ch]:Date.now()+300000}:p.cooldowns});setView("fail")}};
 const setTimeDigit=(i:number,value:string)=>{const digit=value.replace(/\D/g,"").slice(-1);setTimeDigits(timeDigits.map((v,j)=>j===i?digit:v));if(digit&&i<3)setTimeout(()=>document.getElementById(`time-${i+1}`)?.focus(),0)};
 const reset=()=>{localStorage.removeItem(KEY);setP(null);setInput("");setConfirm(false);setView("login")};
 if(!ready)return <main/>;
 if(view==="login")return <Shell><div className="eyebrow">AUTHORIZED RECOVERY TERMINAL</div><h1>THE INDRA<br/><em>DIAMOND</em></h1><p className="lede">Restricted investigation record. Enter the access credential issued by the case controller.</p><label>ENTER ACCESS CREDENTIAL<input autoFocus type="password" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&auth()}/></label>{msg&&<p className="error">{msg}</p>}<Primary onClick={auth}>AUTHENTICATE</Primary><div className="classified">CLASSIFIED <span>•</span> TSD/47/INDRA</div></Shell>;
 if(view==="resume")return <Shell stamp="SESSION ACTIVE"><div className="eyebrow">ACTIVE RECOVERY SESSION DETECTED</div><h2>INVESTIGATIONS<br/>VERIFIED</h2><div className="count">{p?.solved.length} <small>/ 4</small></div><Primary onClick={()=>setView(p?.solved.length===4?"final":cool>0?"fail":"case")}>RESUME INVESTIGATION</Primary><button className="link" onClick={()=>setConfirm(true)}>RESET TERMINAL</button>{confirm&&<Modal cancel={()=>setConfirm(false)} action={reset}/>}</Shell>;
 if(view==="brief")return <Shell stamp="ACCESS VERIFIED"><div className="eyebrow">YOUR INVESTIGATION HAS BEEN AUTHORIZED</div><h2>INITIAL RECOVERY<br/>DOSSIER</h2><div className="dossier">{dossier}</div><p className="center serif">Locate the physical dossier bearing this number.</p><Primary onClick={()=>setView("case")}>BEGIN INVESTIGATION</Primary></Shell>;
 if(view==="status")return <Shell><div className="eyebrow">CASE STATUS / {p?.team} CLEARANCE</div><h2>INVESTIGATIONS VERIFIED</h2><div className="count small">{p?.solved.length} <small>/ 4</small></div><div className="status">{[1,2,3,4].map(n=>{const x=n as Ch;return <div key={n}><span>{C[x].r}</span><b>{p?.solved.includes(x)?C[x].d:"—"}</b><em>{p?.solved.includes(x)?"IMAGE RECOVERED":"IMAGE LOCKED"}</em></div>})}</div>{dossier&&<><h3 className="center">CURRENT AUTHORIZED DOSSIER</h3><div className="dossier mini">{dossier}</div></>}<Primary onClick={()=>setView(p?.solved.length===4?"final":"case")}>RETURN TO INVESTIGATION</Primary></Shell>;
 if(view==="fail")return <Shell stamp="NOT VERIFIED"><div className="eyebrow">CONCLUSION NOT VERIFIED</div>{cool>0?<><h2>ARCHIVAL REVIEW<br/>REQUIRED</h2><p className="lede">Repeated unsupported conclusions have triggered a mandatory evidence review.</p><p className="center">Submission access will reopen in:</p><div className="timer">{countdown(cool)}</div><label>CONTROLLER OVERRIDE<input type="password" autoComplete="off" value={override} onChange={e=>setOverride(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&clean(override)==="VARUNI4415"&&p&&ch){save({...p,cooldowns:{...p.cooldowns,[ch]:0},attempts:{...p.attempts,[ch]:0}});setOverride("");setView("case")}}}/></label><Primary onClick={()=>{if(clean(override)==="VARUNI4415"&&p&&ch){save({...p,cooldowns:{...p.cooldowns,[ch]:0},attempts:{...p.attempts,[ch]:0}});setOverride("");setView("case")}else setMsg("OVERRIDE CODE NOT RECOGNIZED")}}>OVERRIDE REVIEW</Primary>{msg&&<p className="error">{msg}</p>}</>:<><h2>EVIDENCE REMAINS<br/>INCONCLUSIVE</h2><p className="lede">The available evidence does not sufficiently support this conclusion. Re-examine the dossier and submit again.</p><Primary onClick={()=>setView("case")}>RETURN TO EVIDENCE</Primary></>}</Shell>;
 if(view==="reward"&&p){const solved=p.solved.at(-1)!,next=G[p.team].route.find(x=>!p.solved.includes(x[1]));return <Shell stamp="VERIFIED"><div className="eyebrow">{next?"CONCLUSION VERIFIED":"FINAL CONCLUSION VERIFIED"}</div><div className="rewards"><article><h3>LOCK COMPONENT RECOVERED</h3><span>COMPONENT {C[solved].r}</span><strong>{C[solved].d}</strong></article><article><h3>IMAGE FRAGMENT RECOVERED</h3><span>FRAGMENT {C[solved].r}</span><Frag ch={solved}/></article>{next&&<article><h3>NEXT AUTHORIZED DOSSIER</h3><div className="dossier mini">{next[0]}</div><p className="center serif">Locate the physical dossier bearing this number.</p></article>}</div>{!next&&<div className="complete">INVESTIGATIONS COMPLETED <b>4 / 4</b></div>}<Primary onClick={()=>setView(next?"case":"final")}>{next?"CONTINUE INVESTIGATION":"INITIATE FINAL RECONSTRUCTION"}</Primary></Shell>}
 if(view==="final")return <Shell stamp="AUTHORIZED"><div className="eyebrow">ARCHIVAL RECORDS VERIFIED · 4 / 4</div><h2>FINAL LOCATION RECORD<br/><em>RECONSTRUCTED</em></h2><Frag all/><div className="components"><h3>RECOVERED LOCK COMPONENTS</h3>{([1,2,3,4] as Ch[]).map(x=><div key={x}><span>{C[x].r}</span><b>{C[x].d}</b></div>)}</div><div className="authorized"><h2>FINAL RECOVERY<br/>AUTHORIZED</h2><p>The evidence has identified a location.<br/>The recovered components provide access.</p><strong>FIND IT.</strong></div><button className="link" onClick={()=>setView("status")}>VIEW CASE STATUS</button></Shell>;
 if(view==="pin")return <Shell><div className="eyebrow">CONTROLLER ACCESS</div><h2>HOST MODE</h2><label>ENTER CONTROLLER PIN<input autoFocus type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)}/></label>{msg&&<p className="error">{msg}</p>}<Primary onClick={()=>pin==="1947"?(setMsg(""),setView("host")):setMsg("CONTROLLER PIN NOT RECOGNIZED")}>VERIFY PIN</Primary><button className="link" onClick={()=>setView(p?"resume":"login")}>CANCEL</button></Shell>;
 if(view==="host"){const hp=p?.team===hostTeam?p:null;return <Shell stamp="HOST"><div className="eyebrow">LOCAL / DEMO MODE</div><h2>CASE CONTROLLER</h2><div className="tabs">{(Object.keys(G) as Team[]).map(t=><button className={t===hostTeam?"active":""} onClick={()=>setHostTeam(t)} key={t}>{t}</button>)}</div><div className="hostcard"><h3>{hostTeam} TEAM ROUTE</h3>{G[hostTeam].route.map(([d,c])=><div className="hostrow" key={d}><span>{d}</span><b>CHAPTER {c} · {C[c].t}</b><em>{hp?.solved.includes(c)?"SOLVED":"PENDING"}</em><button disabled={hp?.solved.includes(c)} onClick={()=>{let x:P=hp||{team:hostTeam,solved:[],attempts:{},cooldowns:{}};save({...x,solved:[...x.solved,c]})}}>MARK SOLVED</button></div>)}</div><details><summary>EXPECTED ANSWERS</summary><p>Chapter 1: {G[hostTeam].time}<br/>Chapter 2: {G[hostTeam].courier.join(" / ")}<br/>Chapter 3: {G[hostTeam].trip.join(" → ")}<br/>Chapter 4: ASHIRWAD</p></details><div className="hostactions"><button onClick={()=>hp&&save({...hp,cooldowns:{}})}>CLEAR COOLDOWN</button><button onClick={()=>{save({team:hostTeam,solved:[1,2,3,4],attempts:{},cooldowns:{}});setView("final")}}>TEST FINAL</button><button className="danger" onClick={()=>setConfirm(true)}>RESET DEVICE</button></div>{confirm&&<Modal cancel={()=>setConfirm(false)} action={reset}/>}<button className="link" onClick={()=>setView(p?"resume":"login")}>EXIT HOST MODE</button></Shell>}
 return <Shell><div className="casebar"><div><span>AUTHORIZED DOSSIER</span><b>{dossier}</b></div><button onClick={()=>setView("status")}>CASE STATUS</button></div><div className="eyebrow">CHAPTER {ch} / {ch&&C[ch].t}</div><h2>SUBMIT<br/><em>CONCLUSION</em></h2><p className="question">{ch&&C[ch].q}</p>{ch===1?<div className="time-entry"><span className="time-label">RECORDED TIME</span><div>{timeDigits.map((v,i)=><span className="digit-wrap" key={i}><input id={`time-${i}`} inputMode="numeric" maxLength={1} aria-label={`Time digit ${i+1}`} value={v} onFocus={e=>e.currentTarget.select()} onChange={e=>setTimeDigit(i,e.target.value)} onKeyDown={e=>{if(e.key==="Backspace"&&!v&&i>0)setTimeout(()=>document.getElementById(`time-${i-1}`)?.focus(),0);if(e.key==="Enter")check()}}/>{i===1&&<b>:</b>}</span>)}<div className="meridiem"><button className={meridiem==="AM"?"active":""} onClick={()=>setMeridiem("AM")}>AM</button><button className={meridiem==="PM"?"active":""} onClick={()=>setMeridiem("PM")}>PM</button></div></div></div>:ch===3?<div className="journey">{["I","II","III","IV","V","VI"].map((x,i)=><label key={x}><span>{x}</span><input value={trip[i]} onChange={e=>setTrip(trip.map((v,j)=>j===i?e.target.value:v))}/></label>)}</div>:<label>RECORDED CONCLUSION<input autoFocus value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&check()}/></label>}<Primary disabled={!!cool} onClick={check}>SUBMIT CONCLUSION</Primary></Shell>
}
function Modal({cancel,action}:{cancel:()=>void;action:()=>void}){return <div className="modal"><div><h3>ERASE INVESTIGATION RECORD?</h3><p>THIS WILL ERASE ALL INVESTIGATION PROGRESS ON THIS DEVICE.</p><div><button onClick={cancel}>CANCEL</button><button className="danger" onClick={action}>RESET</button></div></div></div>}
