"use client";
import {useEffect,useRef,useState} from "react";
import {G,C,CITY_OPTIONS,COURIER_OPTIONS,LOCK_DIGITS,clean,authenticate,recordFailure,validateConclusion} from "./game-core";import type {Team,Ch} from "./game-core";
type P={team:Team;solved:Ch[];attempts:Partial<Record<Ch,number>>;cooldowns:Partial<Record<Ch,number>>};
type View="login"|"resume"|"brief"|"case"|"fail"|"reward"|"status"|"final"|"pin"|"host";
const LEGACY_KEY="indra-47-state",ACTIVE_KEY="indra-47-active-team",RESET_KEY="indra-47-reset-generation";
const teamKey=(team:Team)=>`indra-47-state-${team.toLowerCase()}`;
function Frag({recoveredCount=0,currentIndex=0,all=false}:{recoveredCount?:number;currentIndex?:number;all?:boolean}){if(all)return <div className="fragment all"><img src="/final-location.jpg" alt="Reconstructed final location record"/><b>FINAL LOCATION RECORD</b></div>;return <div className="fragment-grid" aria-label="Recovered image reconstruction">{([1,2,3,4] as const).map(slot=><div className={`grid-cell ${slot<=recoveredCount?"recovered":"locked"} ${currentIndex===slot?"new":""}`} key={slot}>{slot<=recoveredCount?<img src={`/fragment-${slot}.jpg`} alt={`Recovered image fragment ${slot}`}/>:<span><b>{["I","II","III","IV"][slot-1]}</b>SEALED</span>}</div>)}</div>}
function Header(){const [muted,setMuted]=useState(true),hold=useRef<ReturnType<typeof setTimeout>|null>(null);const cancel=()=>{if(hold.current)clearTimeout(hold.current)};return <header><span>TREASURY SECURITY DIVISION · ARCHIVE 47</span><button onPointerDown={()=>hold.current=setTimeout(()=>window.dispatchEvent(new Event("indra-host")),5000)} onPointerUp={cancel} onPointerLeave={cancel}>CASE 47-ID</button><button className="sound" onClick={()=>setMuted(!muted)}>SOUND {muted?"OFF":"ON"}</button></header>}
function Shell({children,stamp}:{children:React.ReactNode;stamp?:string}){return <main><Header/><section className="paper">{stamp&&<div className="stamp">{stamp}</div>}{children}</section><footer>FICTIONAL ARCHIVAL SYSTEM · AUTHORIZED PERSONNEL ONLY</footer></main>}
function Primary({children,onClick,disabled=false}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button type="button" disabled={disabled} className="primary" onPointerUp={e=>{if(e.pointerType==="touch"){e.preventDefault();onClick()}}} onClick={e=>{if(e.detail===0||!("PointerEvent" in window))onClick();else if((e.nativeEvent as PointerEvent).pointerType!=="touch")onClick()}}>{children}<span>→</span></button>}
function JourneyFields({values,onChange}:{values:string[];onChange:(values:string[])=>void}){return <div className="journey">{["I","II","III","IV","V","VI"].map((roman,i)=><label key={roman}><span>{roman}</span><select id={i===0?"answer-0":`journey-${i}`} aria-label={`Location ${roman}`} value={values[i]} onChange={e=>{onChange(values.map((v,j)=>j===i?e.target.value:v));if(e.target.value&&i<5)setTimeout(()=>document.getElementById(`journey-${i+1}`)?.focus(),0)}}><option value="">SELECT LOCATION</option>{CITY_OPTIONS.map(city=><option value={city} key={city}>{city.toUpperCase()}</option>)}</select></label>)}</div>}
function CourierField({value,onChange}:{value:string;onChange:(value:string)=>void}){return <label>SELECT COURIER<select id="answer-0" className="answer-select" value={value} onChange={e=>onChange(e.target.value)}><option value="">SELECT NAME / IDENTIFIER</option>{COURIER_OPTIONS.map(person=><option value={person.name} key={person.id}>{person.name.toUpperCase()} — {person.id}</option>)}</select></label>}
const countdown=(ms:number)=>`${String(Math.floor(Math.ceil(ms/1000)/60)).padStart(2,"0")}:${String(Math.ceil(ms/1000)%60).padStart(2,"0")}`;
export default function App(){
 const [view,setView]=useState<View>("login"),[p,setP]=useState<P|null>(null),[ready,setReady]=useState(false),[input,setInput]=useState(""),[override,setOverride]=useState(""),[trip,setTrip]=useState(["","","","","",""]),[timeDigits,setTimeDigits]=useState(["","","",""]),[meridiem,setMeridiem]=useState<"AM"|"PM">("PM"),[msg,setMsg]=useState(""),[now,setNow]=useState(Date.now()),[pin,setPin]=useState(""),[hostTeam,setHostTeam]=useState<Team>("RED"),[confirm,setConfirm]=useState(false);
 useEffect(()=>{try{const active=sessionStorage.getItem(ACTIVE_KEY) as Team|null,legacy=localStorage.getItem(LEGACY_KEY);if(legacy){const old=JSON.parse(legacy) as P;localStorage.setItem(teamKey(old.team),legacy);sessionStorage.setItem(ACTIVE_KEY,old.team);localStorage.removeItem(LEGACY_KEY)}const selected=active||((legacy?JSON.parse(legacy).team:null) as Team|null),s=selected&&localStorage.getItem(teamKey(selected));if(s){setP(JSON.parse(s));setView("resume")}}catch{}setReady(true)},[]);useEffect(()=>{const x=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(x)},[]);useEffect(()=>{const open=()=>setView("pin");window.addEventListener("indra-host",open);return()=>window.removeEventListener("indra-host",open)},[]);
 useEffect(()=>{let live=true;const syncReset=async()=>{try{const response=await fetch("/api/reset",{cache:"no-store"});if(!response.ok)return;const {generation}=await response.json() as {generation:number};const seen=Number(localStorage.getItem(RESET_KEY)||generation);if(generation>seen){(Object.keys(G) as Team[]).forEach(team=>localStorage.removeItem(teamKey(team)));sessionStorage.removeItem(ACTIVE_KEY);setP(null);setInput("");setTrip(["","","","","",""]);setView("login")}localStorage.setItem(RESET_KEY,String(generation))}catch{}};syncReset();const timer=setInterval(()=>live&&syncReset(),5000);return()=>{live=false;clearInterval(timer)}},[]);
 const save=(x:P)=>{setP(x);localStorage.setItem(teamKey(x.team),JSON.stringify(x));sessionStorage.setItem(ACTIVE_KEY,x.team)},route=p?G[p.team].route:null,current=route?.find(x=>!p?.solved.includes(x[1])),dossier=current?.[0],ch=current?.[1],cool=ch&&p?.cooldowns[ch]?Math.max(0,p.cooldowns[ch]!-now):0;
 const auth=()=>{const t=authenticate(input);if(!t){setMsg("ACCESS CREDENTIAL NOT RECOGNIZED");return}let existing:P|null=null;try{const saved=localStorage.getItem(teamKey(t));if(saved)existing=JSON.parse(saved)}catch{}save(existing||{team:t,solved:[],attempts:{},cooldowns:{}});setInput("");setMsg("");setView(existing?"resume":"brief")};
 const check=()=>{if(!p||!ch||cool)return;const visibleAnswer=(document.getElementById("answer-0") as HTMLInputElement|null)?.value??input,ok=validateConclusion(p.team,ch,{answer:visibleAnswer,digits:timeDigits,meridiem,trip});if(ok){save({...p,solved:[...p.solved,ch],attempts:{...p.attempts,[ch]:0}});setInput("");setTrip(["","","","",""]);setTimeDigits(["","","",""]);setMeridiem("PM");setView("reward")}else{const expired=!!p.cooldowns[ch]&&p.cooldowns[ch]!<=Date.now(),failed=recordFailure(expired?0:p.attempts[ch]||0,Date.now()),cooldowns={...p.cooldowns};if(expired)delete cooldowns[ch];if(failed.cooldownUntil)cooldowns[ch]=failed.cooldownUntil;save({...p,attempts:{...p.attempts,[ch]:failed.attempts},cooldowns});setView("fail")}};
 const setTimeDigit=(i:number,value:string)=>{const digit=value.replace(/\D/g,"").slice(-1);setTimeDigits(timeDigits.map((v,j)=>j===i?digit:v));if(digit&&i<3)setTimeout(()=>document.getElementById(`time-${i+1}`)?.focus(),0)};
 const clearReview=()=>{if(!p||!ch||clean(override)!=="VARUNI4415"){setMsg("OVERRIDE CODE NOT RECOGNIZED");return}const cooldowns={...p.cooldowns};delete cooldowns[ch];save({...p,cooldowns,attempts:{...p.attempts,[ch]:0}});setInput("");setTrip(["","","","","",""]);setTimeDigits(["","","",""]);setMeridiem("PM");setOverride("");setMsg("");setView("case");setTimeout(()=>document.getElementById(ch===1?"time-0":"answer-0")?.focus(),50)};
 const reset=()=>{if(p)localStorage.removeItem(teamKey(p.team));sessionStorage.removeItem(ACTIVE_KEY);setP(null);setInput("");setConfirm(false);setView("login")};
 const resetAll=async()=>{setMsg("");try{const response=await fetch("/api/reset",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:"VARUNI4415"})});if(!response.ok)throw new Error();const {generation}=await response.json() as {generation:number};(Object.keys(G) as Team[]).forEach(team=>localStorage.removeItem(teamKey(team)));localStorage.setItem(RESET_KEY,String(generation));sessionStorage.removeItem(ACTIVE_KEY);setP(null);setConfirm(false);setInput("");setView("login")}catch{setMsg("GLOBAL RESET COULD NOT BE COMPLETED")}};
 if(!ready)return <main/>;
 if(view==="case"&&Number(ch)===2)return <Shell><div className="casebar"><div><span>{p?.team} TEAM · AUTHORIZED DOSSIER</span><b>{dossier}</b></div><button onClick={()=>setView("status")}>CASE STATUS</button></div><div className="eyebrow">CHAPTER {ch} / {C[2].t}</div><h2>SUBMIT<br/><em>CONCLUSION</em></h2><p className="question">{C[2].q}</p><CourierField value={input} onChange={setInput}/><Primary disabled={!!cool||!input} onClick={check}>SUBMIT CONCLUSION</Primary></Shell>;
 if(view==="login")return <Shell><div className="eyebrow">AUTHORIZED RECOVERY TERMINAL</div><h1>THE INDRA<br/><em>DIAMOND</em></h1><p className="lede">Restricted investigation record. Enter the access credential issued by the case controller.</p><label>ENTER ACCESS CREDENTIAL<input autoFocus type="password" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&auth()}/></label>{msg&&<p className="error">{msg}</p>}<Primary onClick={auth}>AUTHENTICATE</Primary><div className="classified">CLASSIFIED <span>•</span> TSD/47/INDRA</div></Shell>;
 if(view==="resume")return <Shell stamp="SESSION ACTIVE"><div className="eyebrow">{p?.team} TEAM · ACTIVE RECOVERY SESSION</div><h2>INVESTIGATIONS<br/>VERIFIED</h2><div className="count">{p?.solved.length} <small>/ 4</small></div><Primary onClick={()=>setView(p?.solved.length===4?"final":cool>0?"fail":"case")}>RESUME INVESTIGATION</Primary><button className="link" onClick={()=>{sessionStorage.removeItem(ACTIVE_KEY);setP(null);setInput("");setView("login")}}>SWITCH TEAM</button><button className="link" onClick={()=>setConfirm(true)}>RESET THIS TEAM</button>{confirm&&<Modal cancel={()=>setConfirm(false)} action={reset}/>}</Shell>;
 if(view==="brief")return <Shell stamp="ACCESS VERIFIED"><div className="eyebrow">YOUR INVESTIGATION HAS BEEN AUTHORIZED</div><h2>INITIAL RECOVERY<br/>DOSSIER</h2><div className="dossier">{dossier}</div><p className="center serif">Locate the physical dossier bearing this number.</p><Primary onClick={()=>setView("case")}>BEGIN INVESTIGATION</Primary></Shell>;
 if(view==="status")return <Shell><div className="eyebrow">CASE STATUS / {p?.team} CLEARANCE</div><h2>INVESTIGATIONS VERIFIED</h2><div className="count small">{p?.solved.length} <small>/ 4</small></div><div className="status">{[1,2,3,4].map(slot=><div key={slot}><span>{["I","II","III","IV"][slot-1]}</span><b>{slot<=(p?.solved.length||0)?LOCK_DIGITS[slot-1]:"—"}</b><em>{slot<=(p?.solved.length||0)?"IMAGE RECOVERED":"IMAGE LOCKED"}</em></div>)}</div>{dossier&&<><h3 className="center">CURRENT AUTHORIZED DOSSIER</h3><div className="dossier mini">{dossier}</div></>}<Primary onClick={()=>setView(p?.solved.length===4?"final":"case")}>RETURN TO INVESTIGATION</Primary></Shell>;
 if(view==="fail")return <Shell stamp="NOT VERIFIED"><div className="eyebrow">CONCLUSION NOT VERIFIED</div>{cool>0?<><h2>ARCHIVAL REVIEW<br/>REQUIRED</h2><p className="lede">Repeated unsupported conclusions have triggered a mandatory evidence review.</p><p className="center">Submission access will reopen in:</p><div className="timer">{countdown(cool)}</div><label>CONTROLLER OVERRIDE<input type="password" autoComplete="off" value={override} onChange={e=>setOverride(e.target.value)} onKeyDown={e=>e.key==="Enter"&&clearReview()}/></label><Primary onClick={clearReview}>OVERRIDE REVIEW</Primary>{msg&&<p className="error">{msg}</p>}</>:<><h2>EVIDENCE REMAINS<br/>INCONCLUSIVE</h2><p className="lede">The available evidence does not sufficiently support this conclusion. Re-examine the dossier and submit again.</p><Primary onClick={()=>setView("case")}>RETURN TO EVIDENCE</Primary></>}</Shell>;
 if(view==="reward"&&p){const reveal=p.solved.length,next=G[p.team].route.find(x=>!p.solved.includes(x[1]));return <Shell stamp="VERIFIED"><div className="eyebrow">{next?"CONCLUSION VERIFIED":"FINAL CONCLUSION VERIFIED"}</div><div className="rewards"><article><h3>LOCK COMPONENT RECOVERED</h3><span>COMPONENT {["I","II","III","IV"][reveal-1]}</span><strong>{LOCK_DIGITS[reveal-1]}</strong></article><article><h3>IMAGE FRAGMENT RECOVERED</h3><span>FRAGMENT {["I","II","III","IV"][reveal-1]}</span><Frag recoveredCount={reveal} currentIndex={reveal}/></article>{next&&<article><h3>NEXT AUTHORIZED DOSSIER</h3><div className="dossier mini">{next[0]}</div><p className="center serif">Locate the physical dossier bearing this number.</p></article>}</div>{!next&&<div className="complete">INVESTIGATIONS COMPLETED <b>4 / 4</b></div>}<Primary onClick={()=>setView(next?"case":"final")}>{next?"CONTINUE INVESTIGATION":"INITIATE FINAL RECONSTRUCTION"}</Primary></Shell>}
 if(view==="final")return <Shell stamp="AUTHORIZED"><div className="eyebrow">ARCHIVAL RECORDS VERIFIED · 4 / 4</div><h2>FINAL LOCATION RECORD<br/><em>RECONSTRUCTED</em></h2><Frag all/><div className="components"><h3>RECOVERED LOCK COMPONENTS</h3>{([1,2,3,4] as Ch[]).map(x=><div key={x}><span>{C[x].r}</span><b>{C[x].d}</b></div>)}</div><div className="authorized"><h2>FINAL RECOVERY<br/>AUTHORIZED</h2><p>The evidence has identified a location.<br/>The recovered components provide access.</p><strong>FIND IT.</strong></div><button className="link" onClick={()=>setView("status")}>VIEW CASE STATUS</button></Shell>;
 if(view==="pin")return <Shell><div className="eyebrow">CONTROLLER ACCESS</div><h2>HOST MODE</h2><label>ENTER CONTROLLER PIN<input autoFocus type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)}/></label>{msg&&<p className="error">{msg}</p>}<Primary onClick={()=>pin==="1947"?(setMsg(""),setView("host")):setMsg("CONTROLLER PIN NOT RECOGNIZED")}>VERIFY PIN</Primary><button className="link" onClick={()=>setView(p?"resume":"login")}>CANCEL</button></Shell>;
 if(view==="host"){const hp=p?.team===hostTeam?p:null;return <Shell stamp="HOST"><div className="eyebrow">LOCAL / DEMO MODE</div><h2>CASE CONTROLLER</h2><div className="tabs">{(Object.keys(G) as Team[]).map(t=><button className={t===hostTeam?"active":""} onClick={()=>setHostTeam(t)} key={t}>{t}</button>)}</div><div className="hostcard"><h3>{hostTeam} TEAM ROUTE</h3>{G[hostTeam].route.map(([d,c])=><div className="hostrow" key={d}><span>{d}</span><b>CHAPTER {c} · {C[c].t}</b><em>{hp?.solved.includes(c)?"SOLVED":"PENDING"}</em><button disabled={hp?.solved.includes(c)} onClick={()=>{let x:P=hp||{team:hostTeam,solved:[],attempts:{},cooldowns:{}};save({...x,solved:[...x.solved,c]})}}>MARK SOLVED</button></div>)}</div><details><summary>EXPECTED ANSWERS</summary><p>Chapter 1: {G[hostTeam].time}<br/>Chapter 2: {G[hostTeam].courier.join(" / ")}<br/>Chapter 3: {G[hostTeam].trip.join(" → ")}<br/>Chapter 4: ASHIRWAD</p></details><div className="hostactions"><button onClick={()=>hp&&save({...hp,cooldowns:{}})}>CLEAR COOLDOWN</button><button onClick={()=>{save({team:hostTeam,solved:[1,2,3,4],attempts:{},cooldowns:{}});setView("final")}}>TEST FINAL</button><button className="danger" onClick={()=>setConfirm(true)}>RESET THIS TEAM</button><button className="danger" onClick={resetAll}>RESET ALL TEAMS</button></div>{msg&&<p className="error">{msg}</p>}{confirm&&<Modal cancel={()=>setConfirm(false)} action={reset}/>}<button className="link" onClick={()=>setView(p?"resume":"login")}>EXIT HOST MODE</button></Shell>}
 return <Shell><div className="casebar"><div><span>{p?.team} TEAM · AUTHORIZED DOSSIER</span><b>{dossier}</b></div><button onClick={()=>setView("status")}>CASE STATUS</button></div><div className="eyebrow">CHAPTER {ch} / {ch&&C[ch].t}</div><h2>SUBMIT<br/><em>CONCLUSION</em></h2><p className="question">{ch&&C[ch].q}</p>{ch===1?<div className="time-entry"><span className="time-label">RECORDED TIME</span><div>{timeDigits.map((v,i)=><span className="digit-wrap" key={i}><input id={`time-${i}`} inputMode="numeric" maxLength={1} aria-label={`Time digit ${i+1}`} value={v} onFocus={e=>e.currentTarget.select()} onChange={e=>setTimeDigit(i,e.target.value)} onKeyDown={e=>{if(e.key==="Backspace"&&!v&&i>0)setTimeout(()=>document.getElementById(`time-${i-1}`)?.focus(),0);if(e.key==="Enter")check()}}/>{i===1&&<b>:</b>}</span>)}<div className="meridiem"><button className={meridiem==="AM"?"active":""} onClick={()=>setMeridiem("AM")}>AM</button><button className={meridiem==="PM"?"active":""} onClick={()=>setMeridiem("PM")}>PM</button></div></div></div>:ch===3?<JourneyFields values={trip} onChange={setTrip}/>:<label>RECORDED CONCLUSION<input id="answer-0" autoFocus value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&check()}/></label>}<Primary disabled={!!cool||(ch===3&&trip.some(city=>!city))} onClick={check}>SUBMIT CONCLUSION</Primary></Shell>
}
function Modal({cancel,action}:{cancel:()=>void;action:()=>void}){return <div className="modal"><div><h3>ERASE INVESTIGATION RECORD?</h3><p>THIS WILL ERASE ALL INVESTIGATION PROGRESS ON THIS DEVICE.</p><div><button onClick={cancel}>CANCEL</button><button className="danger" onClick={action}>RESET</button></div></div></div>}
